export const FooterData = {
    Data: [{
      title: "F-ZONE",
      // instagram: "instagram.com",
      // facebook: "facebook.com",
      // twitter: "twitter.com",
      // linkedin: "linkedin.com",
      // youtube: "youtube.com",
      contactTitle: "Contact us",
      eTitle: "Shahnoorkhan424@gmail.com",
      // email: "Shahnoorkhan424@gmail.com",
      phoneTitle: "9665911223",
      // phone: "tel:9665911223",
      card1Title: "CORPORATE INFO",
      card1a1Title: "Career at F-ZONE",
      card1a1: " ",
      card1a2Title: "About F_ZONE group",
      card1a2: " ",
      card1a3Title: "Sustainability",
      card1a3: " ",
      card1a4Title: "Press",
      card1a4: " ",
      card2Title: "Help",
      card2a1Title: "Customer Services",
      card2a1: " ",
      card2a2Title: "Contact",
      card2a2: " ",
      card2a3Title: " ",
      card2a3: " ",
      card2a4Title: " ",
      card2a4: " ",
      card3Title: "SHOP",
      card3a1Title: "Women",
      card3a1: "Baby",
      card3a2Title: "Men",
      card3a2: "Kids",
      card3a3Title: " ",
      card3a3: " ",
      card3a4Title: " ",
      card3a4: " ",
      Footer2: " ",
      Date: 2017
    }]
  }